name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip wheel
      - run: pip install bandit black flake8 flake8-bugbear flake8-comprehensions isort safety
      - run: bandit --recursive --skip B101,B104,B310,B311,B303 ./src
      - run: black --check --diff ./src
      - run: flake8 ./src --count --ignore=E203,E266,E731,F401,F811,F841,W503 --max-complexity=15 --max-line-length=120 --show-source --statistics
      - run: isort --check-only --profile black ./src
      - run: safety check
